In [1]:
import numpy as np

In [4]:
# Create 1-D Array 
arr = np.array([10, 20, 30, 40,])
print(arr)
print(np.mean(arr)) # print the average us function np.mean()

[10 20 30 40]
25.0


In [6]:
arr_2d = np.array([[],[],[]])

In [7]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
A = np.zeros((3,3)) # 3 x 3 directory with zeros
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
A = np.ones((2,4)) # 2 rows and 4 column
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
A = np.full((2,3), 4) # 2 rows and 3 columns, all valus 4
print(A)

[[4 4 4]
 [4 4 4]]


In [19]:
A = np.arange(1, 10, 2) # skip 2 element arrange(start, end, skip) start is include but end is excluded
print(A)

[1 3 5 7 9]


In [20]:
A = np.arange(0, 2, 4) # stop value less than skip then only start value is taken
print(A)

[0]


In [22]:
A = np.eye(3) 
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
A = np.linspace(0,10,5) # Five evenly space number fro 0 to 10, included both 0 and 10
print(A)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
#list of random numbers between 0 and 1
A = np.random.rand(10)
print(A)

[0.27710973 0.26514522 0.66898877 0.7514589  0.6971846  0.02177196
 0.14126459 0.23943776 0.91656748 0.899929  ]


In [26]:
# random numbres for 2-D Array
A = np.random.rand(3,2)
print(A)

[[0.72651304 0.5983465 ]
 [0.4168635  0.73941811]
 [0.57653155 0.68968714]]


In [31]:
# random number not in between 0 and 1
A = np.random.randint(10, 100, size = (2,3))
print(A)

[[96 88 20]
 [57 17 98]]


In [33]:
# random number not in between 0 and 1, Array of 5 integers
A = np.random.randint(10, 100, size = (5))
print(A)
print(np.mean(A)) # find average of newly created array

[99 18 69 90 72]
69.6


In [35]:
A = np.array([[1, 2],[4, 5],[7, 8],[3,4]])
print(A)

[[1 2]
 [4 5]
 [7 8]
 [3 4]]


In [38]:
#reshape of array A(2, 4) to B(4,2)
B = A.reshape((4,2)) #original  array A reshape to (4,2) 
print(B)

[[1 2]
 [4 5]
 [7 8]
 [3 4]]


In [42]:
#flatten or raval to convert 20D Array to 1-D 
B = B.flatten()
print(B)
C = A.ravel()
print(C)

[1 2 4 5 7 8 3 4]
[1 2 4 5 7 8 3 4]
